import mongoose from 'mongoose';

const userSchema = new mongoose.Schema({
    name: String,
    pemail: String,
    dfemail: String,
    github: String,
    linkedin: String,
    phone: String,
    cohort: String,
    learning: String,
    trainer: String,
    grade: String,
    traineeFinishingDate: String,
    challengeOne: String,
    challengeTwo: String,
    challengeThree: String,
    challengeFour: String,
    challengeFive: String,
    challengeSix: String,
    degreeInstitution: String,
    degreeSubject: String,
    degreeLevel: String,
    degreeGrade: String,
    degreeDateFrom: String,
    degreeDateTo: String,
    degreeDescription: String,
    school: String,
    schoolExamType: String,
    schoolSubject: String,
    schoolGrade: String,
    schoolYear: String,
    schoolDescription: String,
    workExperience: String,
    workInstitution: String,
    workPosition: String,
    workDateFrom: String,
    workDateTo: String,
    workDescription: String,
    awardType: String,
    awardIssuer: String,
    award: String,
    awardGrade: String,
    dateAwarded: String,
    awardDescription: String,
    portfolioTitle: String,
    url: String,
    portfolioDescription: String,
});

const User = new mongoose.model("User", userSchema);

export default User;